title: Febri's Portfolio
logo: /assets/img/logo.png
description: Digital Consultant, MSc Business Analytics - The University of Edinburgh
show_downloads: false
google_analytics:
future: true
theme: jekyll-theme-minimal
